debug: true
prefix: "§6[玩家等级]"
type: "formula"
experience:
  1-30: 500 + ( ( level - 1 ) * 200 )
  31-40: 500 + ( ( level - 1 ) * 400 )
  41: 500 + ( ( level - 1 ) * 600 )
defaultLevel: 1
save_timer: 300
save_tips: true
messages:
  level_up: "§a升到了 §b%level% §a级"
  get_experience: "§a获得 §b%experience% §a经验"
  level_reset: "§a等级重置"

